// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lifdhyyghyntmmidujnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpZmRoeXlnaHludG1taWR1am5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTI5ODEsImV4cCI6MjA2NTQ2ODk4MX0.L3wSNYqpd_1IKKMQ3PuMI4btSaB3o2D6pc4edlGdl8c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);